### ISSUE TITLE
Pre-built files

### ISSUE THREAD

**Issue by clairetsai818** [wilddeer/Peppermint#12]
Hi, I am a member of [CDNJS](https://github.com/cdnjs/cdnjs), we're going to host this great lib in our CDN. We're wondering if we need to host `peppermint.pure.js` as well. Thanks!

https://github.com/cdnjs/cdnjs/pull/10856

**Comment by wilddeer** [comment]
Short answer is no, you shouldn’t host it. It misses the required dependency.
