### ISSUE TITLE
Recieve slider object as parameter in onSlideChange

### ISSUE THREAD

**Issue by doxadoxa** [wilddeer/Peppermint#6]
Hello, thanks for your slider!

What do you think about receive slider object as parameter in callback onSlideChange?

**Comment by wilddeer** [comment]
what's the purpose?

**Comment by doxadoxa** [comment]
Hiding control arrows when edge of slider reached. When use more, than one slider on page.

**Comment by wilddeer** [comment]
Slider object is returned upon initialization. Nothing prevents you from using it in a callback.
